### PR TITLE
Adding some more emojis + changing some

### PR DESCRIPTION
**Pull request by lineville**
## Changes

- Cleanup Readme from markdown format suggestions + updated with some file extension additions
- Swap out several emojis for others
- Add a few emojis for file extensions

### CODE REVIEW

**Review by mightbesimon — APPROVED** [review]
Lovely, thank you Liam! I'll approve for now
There are two files that needs updating too, `file-icons/emoji-reference.md` and `product-icons/emoji-reference.md`. I'll do these when I get back from my holiday and do a release.

**Comment by mightbesimon** [comment]
great catch on the extra space in `README.md`! 😁

**Comment by lineville** [comment]
@mightbesimon Sounds good appreciate it 😄

**Comment by lineville** [comment]
@JakeBriscoe Why was this closed?

**Pull request closed without merging**
